name: build

on: [push, pull_request]

jobs:
  build_thrift_jackson_modules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        thrift_version: [ '0.10.0', '0.13.0' ]
    name: Build thrift-jackson modules for Apache Thrift version ${{ matrix.thrift_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build thrift-jackson (Thrift ${{ matrix.thrift_version }})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} sbt build-thrift-jackson

  build_scrooge_jackson_modules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: Build scrooge-jackson modules
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build scrooge-jackson
        run: THRIFT_VERSION=0.10.0 sbt build-scrooge-jackson

  build_thrift_spark_modules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        thrift_version: [ '0.10.0', '0.13.0' ]
        spark_profile: ['spark2', 'spark3']
    name: Build thrift-spark modules for Apache Thrift version ${{ matrix.thrift_version }} and Apache Spark profile ${{ matrix.spark_profile }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build spark-commons (Thrift ${{ matrix.thrift_version }}, Spark ${{matrix.spark_profile}})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} SPARK_PROFILE=${{matrix.spark_profile}} sbt build-spark-commons
      - name: Build thrift-spark (Thrift ${{ matrix.thrift_version }}, Spark ${{matrix.spark_profile}})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} SPARK_PROFILE=${{matrix.spark_profile}} sbt build-thrift-spark
  build_scrooge_spark_modules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        spark_profile: [ 'spark2', 'spark3' ]
    name: Build scrooge-spark modules for Apache Spark profile ${{ matrix.spark_profile }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build spark-commons (Spark ${{matrix.spark_profile}})
        run: THRIFT_VERSION=0.10.0 SPARK_PROFILE=${{matrix.spark_profile}} sbt build-spark-commons
      - name: Build scrooge-spark (Spark ${{matrix.spark_profile}})
        run: THRIFT_VERSION=0.10.0 SPARK_PROFILE=${{matrix.spark_profile}} sbt build-scrooge-spark
  build_thrift_flink_modules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        thrift_version: [ '0.10.0', '0.13.0']
        flink_profile: [ 'flink1_13', 'flink1_14', 'flink1_15']
    name: Build thrift-flink modules for Apache Thrift version ${{ matrix.thrift_version }} and Flink profile ${{matrix.flink_profile}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build flink-commons (Thrift ${{ matrix.thrift_version }}, Flink ${{ matrix.flink_profile }})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} FLINK_PROFILE=${{ matrix.flink_profile }} sbt build-flink-commons
      - name: Build thrift-flink (Thrift ${{ matrix.thrift_version }}, Flink ${{ matrix.flink_profile }})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} FLINK_PROFILE=${{ matrix.flink_profile }} sbt build-thrift-flink
  build_scrooge_flink_modules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        flink_profile: [ 'flink1_13', 'flink1_14', 'flink1_15' ]
    name: Build scrooge-flink modules for Flink profile ${{matrix.flink_profile}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build flink-commons (Flink ${{ matrix.flink_profile }})
        run: THRIFT_VERSION=0.10.0 FLINK_PROFILE=${{ matrix.flink_profile }} sbt build-flink-commons
      - name: Build thrift-flink (Flink ${{ matrix.flink_profile }})
        run: THRIFT_VERSION=0.10.0 FLINK_PROFILE=${{ matrix.flink_profile }} sbt build-thrift-flink