name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thrift_version: [ '0.10.0', '0.13.0' ]
    name: Build for Thrift version ${{ matrix.thrift_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build parsimonious-commons (thrift ${{ matrix.thrift_version }})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} sbt build-commons
      - name: Build parsimonious-jackson (thrift ${{ matrix.thrift_version }})
        run: THRIFT_VERSION=${{ matrix.thrift_version }} sbt build-jackson
      - name: Build parsimonious-spark (thrift ${{ matrix.thrift_version }}, spark 2.4)
        run: THRIFT_VERSION=${{ matrix.thrift_version }} SPARK_PROFILE=spark2 sbt build-spark
      - name: Build parsimonious-spark (thrift ${{ matrix.thrift_version }}, spark 3.2)
        run: THRIFT_VERSION=${{ matrix.thrift_version }} SPARK_PROFILE=spark3 sbt build-spark

#      - name: Publish parsimonious-commons (thrift ${{ matrix.thrift_version }})
#        run: THRIFT_VERSION=${{ matrix.thrift_version }} sbt publish-commons
#      - name: Publish parsimonious-jackson (thrift ${{ matrix.thrift_version }})
#        run: THRIFT_VERSION=${{ matrix.thrift_version }} sbt publish-jackson
#      - name: Publish parsimonious-spark (thrift ${{ matrix.thrift_version }}, spark 2.4)
#        run: THRIFT_VERSION=${{ matrix.thrift_version }} SPARK_PROFILE=spark2 sbt publish-spark
#      - name: Publish parsimonious-spark (thrift ${{ matrix.thrift_version }}, spark 3.2)
#        run: THRIFT_VERSION=${{ matrix.thrift_version }} SPARK_PROFILE=spark3 sbt publish-spark
    env:
      GITHUB_TOKEN: ${{ github.token }}