name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
      - name: Build parsimonious-commons (thrift 0.10)
        run: THRIFT_VERSION=0.10.0 sbt build-commons
      - name: Build parsimonious-jackson (thrift 0.10)
        run: THRIFT_VERSION=0.10.0 sbt build-jackson
      - name: Build parsimonious-spark (thrift 0.10, spark 2.4)
        run: THRIFT_VERSION=0.10.0 SPARK_PROFILE=spark2 sbt build-spark
      - name: Build parsimonious-spark (thrift 0.10, spark 3.2)
        run: THRIFT_VERSION=0.10.0 SPARK_PROFILE=spark3 sbt build-spark
      - name: Build parsimonious-commons (thrift 0.13)
        run: THRIFT_VERSION=0.13.0 sbt build-commons
      - name: Build parsimonious-jackson (thrift 0.13)
        run: THRIFT_VERSION=0.13.0 sbt build-jackson
      - name: Build parsimonious-spark (thrift 0.13, spark 2.4)
        run: THRIFT_VERSION=0.13.0 SPARK_PROFILE=spark2 sbt build-spark
      - name: Build parsimonious-spark (thrift 0.13, spark 3.2)
        run: THRIFT_VERSION=0.13.0 SPARK_PROFILE=spark3 sbt build-spark
    env:
      GITHUB_TOKEN: ${{ github.token }}